name: Test and lint

on:
    push:
        branches: tree_hyperopt
    pull_request:
        branches: [ tree_hyperopt, main ]

permissions:
    contents: read

jobs:
    flake8_py3:
        runs-on: ubuntu-latest
        steps:
          - name: Setup Python
            uses: actions/setup-python@v3
            with:
                python-version: 3.10.6

          - name: Checkout
            uses: actions/checkout@v3

          - name: Install flake8
            run: pip install flake8

          - name: Run flake8
            uses: py-actions/flake8@v2
            with:
                path: DecisionTrees
                max-line-length: 120
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    pytest:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Setup Python 3.10
            uses: actions/setup-python@v3
            with:
                python-version: 3.10.6

          - name: Install Dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r DecisionTrees/requirements.txt

          - name: Run pytest
            run: |
                pytest

